[package]
name = "helper"
description = "Shared helper utilities for fishnet workspace"
publish = false
version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
approx.workspace = true
log.workspace = true
log4rs.workspace = true
thiserror.workspace = true

[lib]
path = "src/lib.rs"
