[package]
name = "fishnet"
version = "0.1.0"
edition = "2021"
description = "Fast CLI tool for nanopore signal to sequence alignment"
license-file = "./LICENSE"
repository = "https://github.com/dietvin/fishnet"

[package.metadata.release]
# Don't publish to crates.io (since this seems to be a standalone binary)
publish = false
# Don't push to registry
registry = false
# Custom pre-release hooks (optional)
pre-release-hook = ["git", "diff", "--exit-code"]
# Custom post-release hooks (optional)
post-release-hook = ["echo", "Released {{version}}"]
# Tag message template
tag-message = "Release {{crate_name}} {{version}}"
# Don't create a release branch
dev-version = false

[dependencies]
approx = "0.5.1"
arrow = "55.0.0"
clap = "4.5.37"
console = "0.15.11"
crossbeam = "0.8.4"
indicatif = "0.17.11"
itertools = "0.14.0"
log = "0.4.27"
log4rs = "1.3.0"
noodles = { version = "0.99.0", features = ["bam", "bgzf", "sam"] }
parquet = "55.0.0"
pod5 = { git = "https://github.com/bsaintjo/pod5-rs", rev = "e9335fef0ee6f7bcdeb72ccdd52cc98debddf361", version = "0.1.0" }
rand = "0.9.0"
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.11"
uuid = "1.16.0"
walkdir = "2.5.0"
