[package]
name = "fishnet"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
bitvec = "1.0.1"
interp = "2.0.2"
itertools = "0.14.0"
pod5 = { git = "https://github.com/bsaintjo/pod5-rs", version = "0.1.0" }
polars = { version = "0.46.0", features = ["lazy", "rows"] }
rand = "0.9.0"
rust-htslib = "0.46.0"
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.11"
uuid = "1.12.1"
walkdir = "2.5.0"
