[package]
name = "fishnet"
description = "Fast CLI tool for nanopore signal to sequence alignment"
version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
alignment = { path = "../alignment" }
reformat = { path = "../reformat" }

clap.workspace = true
console.workspace = true
log.workspace = true
thiserror.workspace = true

[[bin]]
name = "fishnet"
path = "src/main.rs"