[package]
name = "fishnet"
version = "0.2.1"
edition = "2024"
description = "Fast CLI tool for nanopore signal to sequence alignment"
license-file = "../LICENSE"
repository = "https://github.com/dietvin/fishnet"

[dependencies]
alignment = { path = "../alignment" }
clap = { version = "4.5.46", features = ["cargo"] }
console = "0.16.0"
log = "0.4.27"
thiserror.workspace = true
