name: Build Docs
permissions:
    contents: write
on:
    push:
        tags:
            - 'v*'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-verison: '3.x'
            - run: pip install mkdocs-material
            - run: mkdocs gh-deploy --force